### PR TITLE
feat: add AAS AID tooling

### PR DESCRIPTION
**Pull request by danielpeintner**
I took over AID code from node-wot td-tools.

# What is working:
* `npm run build`
* `npm run test`

#  TODOs/ To be decided
* [X] version number to use ? `"1.0.0"` ? see https://github.com/eclipse-thingweb/td-tools/pull/7/commits/c7a66eafa56708dcb358f8978bc518fa1af0c0a9
* [x] update examples
   * [X]  remove browser example since there is no wot-bundle.min.js and I don't think it is worth building such just for AID, see https://github.com/eclipse-thingweb/td-tools/pull/7/commits/25989fd745b7b7b02bd96d306c77a7b708a19ce4
* [X] remove deprecated method, see https://github.com/eclipse-thingweb/td-tools/pull/7/commits/1b54f9cb6a15b58d084a98c3c66046f481003b8e
* renaming 
  * [X] of files see https://github.com/eclipse-thingweb/td-tools/pull/7/commits/23dcfb6a89bdc20598346032a7e5ec950baa9d73
  * [X] methods? We have the following public methods and I would like to rename some of them
    * `transformAAS2TD(...)` --> fine
    * `transformTD2AAS(...)` --> fine
    * `transformSM2TD(...)`  --> not sure if "SM" for sub-model should be used, maybe `transformAID2TD(...)` ??
    * `transformTD2SM(...)`  --> same as above
    * RESOLUTION, we have two _public_ methods only
      * `transformAID2TD(aasAID: string, template?: string, submodelRegex?: string): string`
        * auto-detect whether we get full AAS or AID submodel only
      * `transformTD2AID(td: string, options?: Options, protocols?: string[]): string`
        * by default AID submodel is created but an option `createAAS` can be passed to get a full AAS
* [x] update plural, see https://github.com/eclipse-thingweb/node-wot/issues/1235, see https://github.com/eclipse-thingweb/td-tools/pull/7/commits/487ffb529014070217ad2a9a9f1a2e06b1b6f3a0

### CODE REVIEW

**Comment by danielpeintner** [comment]
> We had a quick look and I think we should not have the eslint and prettier in each tool folder. There are root configs available and seem similar.

Makes sense. I didn't even look at the root level. Anyhow, I noticed some shortcoming w.r.t. to the current setup.
* in node-wot we used to have `eslint-plugin-unused-imports`. I think having this might be useful
* I also noticed that "npm run lint" does not _screem_ if I have unused variables in my code. Useful again I think.
* I also wonder whether prettier & linting should be based on language level (hence moving it into the `/node` directory )

Hence, I opened a dedicated issue for it (TODO Link)

BTW, the PR is now ready for review!

**Review by sebastiankb — APPROVED** [review]

**Comment by egekorkan** [comment]
We have discussed in the call:
- We will adopt version 1.0.0
- Browserified version should just work. In Playground, we install via npm and use the dist folder outputs. Since AID tooling has no Node.js dependency (in first glance), it should be just fine. We can remove the browser example and just point to Playground. The bundled version can be mentioned in the readme as the output of dist folder.
- The function names discussion:
  - We should get input from Sebastian and users of AAS
  - Ege's preference is to have only two functions where "AAS wrapper or not" is another argument.

**Comment by danielpeintner** [comment]
The PR is now ready for review. As discussed there are now two _public_ methods only

* `transformAID2TD(aasAID: string, template?: string, submodelRegex?: string): string`
  * auto-detect whether we get full AAS or AID submodel only
* `transformTD2AID(td: string, options?: Options, protocols?: string[]): string`
   * by default AID submodel is created but an option `createAAS` can be passed to get a full AAS

**Review by egekorkan — APPROVED** [review]

**Comment by danielpeintner** [comment]
@sebastiankb @Kaz040 are the revised public method names (see https://github.com/eclipse-thingweb/td-tools/pull/7#issuecomment-2045585034) fine by you?

**Comment by Kaz040** [comment]
> @sebastiankb @Kaz040 are the revised public method names (see [#7 (comment)](https://github.com/eclipse-thingweb/td-tools/pull/7#issuecomment-2045585034)) fine by you?

@danielpeintner , The names are ok for me.

**Comment by sebastiankb** [comment]
its perfect for me. ready for merge

**Comment by danielpeintner** [comment]
FYI: aas-aid package available on NPM (see https://www.npmjs.com/package/@thingweb/aas-aid)

**Comment by mrtnzagustin** [comment]
Guys, sorry for adding a comment here but I am not able to use/reach the transformTD2AAS function. Do you have any example of how to use it? is it already implemented?

**Comment by danielpeintner** [comment]
An example is given in the [NPM readme](https://www.npmjs.com/package/@thingweb/aas-aid) of or can be found also [at the new home](https://github.com/eclipse-thingweb/td-tools/tree/main/node/aas-aid#aasaid-to-wot-td).

Note: the naming of the functions has been slightly changed (e.g., `transformAID2TD(...)`).

**Comment by mrtnzagustin** [comment]
Those two are working fine, but the one that generates the AASX (transformTD2AAS) format is missed.
image

image

**Comment by mrtnzagustin** [comment]
Mmmm I saw this comment: 
"transformTD2AID(td: string, options?: Options, protocols?: string[]): string -> by default AID submodel is created but an option createAAS can be passed to get a full AAS"

Do I need to use the createAAS parameter? We may need to update the documentation to reflect that approach.

**Comment by danielpeintner** [comment]
> Mmmm I saw this comment: "transformTD2AID(td: string, options?: Options, protocols?: string[]): string -> by default AID submodel is created but an option createAAS can be passed to get a full AAS"
> 
> Do I need to use the createAAS parameter? We may need to update the documentation to reflect that approach.

Yes, correct. As mentioned in the example
https://github.com/eclipse-thingweb/td-tools/blob/ee21893c6595d9e458cc28820e1e913c61e064a5/node/aas-aid/README.md?plain=1#L93

Do you think we should improve the documentation?
Please feel free to provide a PR to https://github.com/eclipse-thingweb/td-tools/blob/main/node/aas-aid/README.md

**Pull request merged**
